Disable tests (for now)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,38 +25,38 @@ jobs:
           docker compose up -d
           docker compose exec nginx /usr/sbin/nginx -s reload
 
-  test:
-    runs-on: ubuntu-latest
-    needs:
-      - deploy
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: lts/iron
-      - name: Install test dependencies
-        run: npm ci
-      - name: Install Playwright browsers
-        run: npx playwright install --with-deps
-      - name: Run Playwright tests
-        run: TEST_DOMAIN=https://develop.tna.dblclk.dev CI=true npx playwright test
-      - uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: playwright-report
-          path: playwright-report/
-          retention-days: 30
+  # test:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - deploy
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: lts/iron
+  #     - name: Install test dependencies
+  #       run: npm ci
+  #     - name: Install Playwright browsers
+  #       run: npx playwright install --with-deps
+  #     - name: Run Playwright tests
+  #       run: TEST_DOMAIN=https://develop.tna.dblclk.dev CI=true npx playwright test
+  #     - uses: actions/upload-artifact@v4
+  #       if: always()
+  #       with:
+  #         name: playwright-report
+  #         path: playwright-report/
+  #         retention-days: 30
 
-  cleanup:
-    runs-on: ubuntu-latest
-    needs:
-      - test
-    steps:
-    - uses: appleboy/ssh-action@v1.0.3
-      with:
-        host: ${{ secrets.SSH_HOST }}
-        username: ${{ secrets.SSH_USERNAME }}
-        password: ${{ secrets.SSH_PASSWORD }}
-        port: ${{ secrets.SSH_PORT }}
-        script: if df -hP -k /dev/sda1 | awk '{if ($5+0>=80) exit 1}'; then echo "Space OK"; else docker system prune --force --all --volumes; fi
+  # cleanup:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - test
+  #   steps:
+  #   - uses: appleboy/ssh-action@v1.0.3
+  #     with:
+  #       host: ${{ secrets.SSH_HOST }}
+  #       username: ${{ secrets.SSH_USERNAME }}
+  #       password: ${{ secrets.SSH_PASSWORD }}
+  #       port: ${{ secrets.SSH_PORT }}
+  #       script: if df -hP -k /dev/sda1 | awk '{if ($5+0>=80) exit 1}'; then echo "Space OK"; else docker system prune --force --all --volumes; fi
   
